export { ReactComponent as ChevronLeftIcon } from 'assets/icons/chevron_left.svg'
export { ReactComponent as EmailIcon } from 'assets/icons/email.svg'
export { ReactComponent as UserIcon } from 'assets/icons/user.svg'
export { ReactComponent as HomeIcon } from 'assets/icons/home.svg'
export { ReactComponent as QuotesStartIcon } from 'assets/icons/quotes-start.svg'
export { ReactComponent as QuotesEndIcon } from 'assets/icons/quotes-end.svg'
export { ReactComponent as GithubIcon } from 'assets/icons/github.svg'
export { ReactComponent as NotionIcon } from 'assets/icons/notion.svg'
